name: splitwise_api
description: >-
  A Wrapper over SplitWise API
version: 0.0.1
homepage: https://github.com/srthkpthk/splitwise_api
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  oauth1: ^1.0.4
