name: splitwise_api
description: >-
   A Wrapper over SplitWise API.
   * Uses OAuth 1 as Authentication.
   *  Includes all methods stated on SplitWise DEV website.
version: 2.0.5
homepage: https://github.com/srthkpthk/splitwise_api
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  oauth1: ^2.0.0
  json_serializable: ^6.0.0
  json_annotation: ^4.1.0
dev_dependencies:
  build_runner: ^2.1.2

