name: splitwise_api
description: >-
   A Wrapper over SplitWise API.
   * Uses OAuth 1 as Authentication.
   *  Includes all methods stated on SplitWise DEV website.
version: 2.0.0
homepage: https://github.com/srthkpthk/splitwise_api
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  oauth1: ^2.0.0
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
dev_dependencies:
  build_runner: ^2.0.4

