import 'package:json_annotation/json_annotation.dart';

import 'enums.dart';
import 'image_set.dart';

part 'comment.g.dart';

/// The abbreviated user object nested in comments and expense shares.
@JsonSerializable()
class CommentUser {
  /// Creates a comment user.
  const CommentUser({
    required this.id,
    this.firstName,
    this.lastName,
    this.picture,
  });

  /// Deserializes a comment user.
  factory CommentUser.fromJson(Map<String, dynamic> json) =>
      _$CommentUserFromJson(json);

  /// Unique identifier of the user.
  final int id;

  /// The user's first name.
  final String? firstName;

  /// The user's last name.
  final String? lastName;

  /// The user's profile picture.
  final ImageSet? picture;

  /// Serializes this comment user.
  Map<String, dynamic> toJson() => _$CommentUserToJson(this);
}

/// A comment on an expense.
@JsonSerializable()
class Comment {
  /// Creates a comment.
  const Comment({
    required this.id,
    this.content,
    this.commentType,
    this.relationType,
    this.relationId,
    this.createdAt,
    this.deletedAt,
    this.user,
  });

  /// Deserializes a comment.
  factory Comment.fromJson(Map<String, dynamic> json) =>
      _$CommentFromJson(json);

  /// Unique identifier of the comment.
  final int id;

  /// The comment text.
  final String? content;

  /// Whether the comment was written by a user or generated by Splitwise.
  @JsonKey(unknownEnumValue: CommentType.unknown)
  final CommentType? commentType;

  /// The kind of object the comment is attached to.
  @JsonKey(unknownEnumValue: RelationType.unknown)
  final RelationType? relationType;

  /// ID of the object the comment is attached to (the expense ID).
  final int? relationId;

  /// When the comment was created.
  final DateTime? createdAt;

  /// When the comment was deleted, if it has been.
  final DateTime? deletedAt;

  /// The author of the comment.
  final CommentUser? user;

  /// Serializes this comment.
  Map<String, dynamic> toJson() => _$CommentToJson(this);
}
