import 'package:json_annotation/json_annotation.dart';

/// Registration state of a Splitwise user.
@JsonEnum(valueField: 'wireName')
enum RegistrationStatus {
  /// The user has confirmed their account.
  confirmed('confirmed'),

  /// A placeholder user created without an email address.
  dummy('dummy'),

  /// The user has been invited but has not yet joined.
  invited('invited'),

  /// A value not known to this version of the package.
  ///
  /// Returned when the API sends a status this package does not recognise.
  /// Do not send it in requests.
  unknown('unknown');

  const RegistrationStatus(this.wireName);

  /// The value used on the wire.
  final String wireName;
}

/// Type of a Splitwise group.
@JsonEnum(valueField: 'wireName')
enum GroupType {
  home('home'),
  trip('trip'),
  couple('couple'),
  other('other'),
  apartment('apartment'),
  house('house'),

  /// A value not known to this version of the package.
  ///
  /// Returned when the API sends a type this package does not recognise.
  /// Do not send it in requests.
  unknown('unknown');

  const GroupType(this.wireName);

  /// The value used on the wire.
  final String wireName;
}

/// How often a repeating expense recurs.
@JsonEnum(valueField: 'wireName')
enum RepeatInterval {
  never('never'),
  weekly('weekly'),
  fortnightly('fortnightly'),
  monthly('monthly'),
  yearly('yearly'),

  /// A value not known to this version of the package.
  ///
  /// Returned when the API sends an interval this package does not recognise.
  /// Do not send it in requests.
  unknown('unknown');

  const RepeatInterval(this.wireName);

  /// The value used on the wire.
  final String wireName;
}

/// Origin of a comment on an expense.
@JsonEnum(valueField: 'wireName')
enum CommentType {
  /// Generated by Splitwise (for example "X added this expense").
  system('System'),

  /// Written by a user.
  user('User'),

  /// A value not known to this version of the package.
  unknown('unknown');

  const CommentType(this.wireName);

  /// The value used on the wire.
  final String wireName;
}

/// The kind of object a comment is attached to.
@JsonEnum(valueField: 'wireName')
enum RelationType {
  expenseComment('ExpenseComment'),

  /// A value not known to this version of the package.
  unknown('unknown');

  const RelationType(this.wireName);

  /// The value used on the wire.
  final String wireName;
}

/// Shape of a notification's image.
@JsonEnum(valueField: 'wireName')
enum ImageShape {
  square('square'),
  circle('circle'),

  /// A value not known to this version of the package.
  unknown('unknown');

  const ImageShape(this.wireName);

  /// The value used on the wire.
  final String wireName;
}
